### PR TITLE
Docker setup

### PR DESCRIPTION
**Pull request by karthik137**
Created docker-compose file to setup node-explorer. Cordapps path can be set using environment variable. 

Tested the docker-compose file in ubuntu 16.04

Demo link --> https://www.youtube.com/watch?v=fcW4UdELkmM

Closes issue #6

### CODE REVIEW

**Comment by karthik137** [comment]
kirito37/node-server:v0.1.0  and kirito37/node-explorer:v0.1.0 images are pushed to dockerhub.

**Comment by anixon604** [comment]
Hi @karthik137 thanks for this, will try and get this in today. :)

**Comment by karthik137** [comment]
ok :)

**Comment by anixon604** [comment]
LGTM. will make some small README edits. but this is a great addition. Thanks!

**Pull request merged**
